// Code generated by gowrap. DO NOT EDIT.
// template: ../../gowrap/errwrap.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package executor

import (
	"context"
	"fmt"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// ExecutorWithErrWrap wraps errors from Executor with operation context.
type ExecutorWithErrWrap struct {
	_base Executor
}

// NewExecutorWithErrWrap returns a ExecutorWithErrWrap wrapping the given base implementation.
func NewExecutorWithErrWrap(base Executor) Executor {
	return &ExecutorWithErrWrap{_base: base}
}

// ExecBatch implements Executor.
func (_d *ExecutorWithErrWrap) ExecBatch(arg0 context.Context, arg1 *pgx.Batch) (err error) {
	const op = "postgres.Executor.ExecBatch"
	err = _d._base.ExecBatch(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// GetExecutor implements Executor.
func (_d *ExecutorWithErrWrap) GetExecutor(arg0 context.Context) (q1 QueryExecutor) {
	const op = "postgres.Executor.GetExecutor"
	q1 = _d._base.GetExecutor(arg0)
	return
}

// GetPoolExecutor implements Executor.
func (_d *ExecutorWithErrWrap) GetPoolExecutor() (pp1 *pgxpool.Pool) {
	const op = "postgres.Executor.GetPoolExecutor"
	pp1 = _d._base.GetPoolExecutor()
	return
}

// GetTxExecutor implements Executor.
func (_d *ExecutorWithErrWrap) GetTxExecutor(arg0 context.Context) (t1 pgx.Tx, err error) {
	const op = "postgres.Executor.GetTxExecutor"
	t1, err = _d._base.GetTxExecutor(arg0)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// InjectTxExecutor implements Executor.
func (_d *ExecutorWithErrWrap) InjectTxExecutor(arg0 context.Context, arg1 pgx.Tx) (c2 context.Context, err error) {
	const op = "postgres.Executor.InjectTxExecutor"
	c2, err = _d._base.InjectTxExecutor(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}
