// Code generated by ifacemaker; DO NOT EDIT.

package executor

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
)

// Executor ...
type Executor interface {
	GetExecutor(ctx context.Context) QueryExecutor
	GetPoolExecutor() *pgxpool.Pool
	GetTxExecutor(ctx context.Context) (pgx.Tx, error)
	InjectTxExecutor(ctx context.Context, tx pgx.Tx) (context.Context, error)
	ExecBatch(ctx context.Context, batch *pgx.Batch) error
}
