// Code generated by ifacemaker; DO NOT EDIT.

package tx

import (
	"context"
)

// Manager ...
type Manager interface {
	IsTx(ctx context.Context) error
	// WithTransaction runs fn in a transaction stored in ctx.
	//
	// If ctx already carries a transaction, fn joins it: commit and rollback are
	// up to whoever started it. An error returned by fn or a panic rolls the
	// transaction back.
	WithTransaction(ctx context.Context, fn func(context.Context) error) error
}
