// Code generated by gowrap. DO NOT EDIT.
// template: ../../gowrap/errwrap.tmpl
// gowrap: http://github.com/hexdigest/gowrap

package tx

import (
	"context"
	"fmt"
)

// ManagerWithErrWrap wraps errors from Manager with operation context.
type ManagerWithErrWrap struct {
	_base Manager
}

// NewManagerWithErrWrap returns a ManagerWithErrWrap wrapping the given base implementation.
func NewManagerWithErrWrap(base Manager) Manager {
	return &ManagerWithErrWrap{_base: base}
}

// IsTx implements Manager.
func (_d *ManagerWithErrWrap) IsTx(arg0 context.Context) (err error) {
	const op = "postgres.tx.Manager.IsTx"
	err = _d._base.IsTx(arg0)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}

// WithTransaction implements Manager.
func (_d *ManagerWithErrWrap) WithTransaction(arg0 context.Context, arg1 func(context.Context) error) (err error) {
	const op = "postgres.tx.Manager.WithTransaction"
	err = _d._base.WithTransaction(arg0, arg1)
	if err != nil {
		err = fmt.Errorf("%s: %w", op, err)
	}
	return
}
